### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by csbeer** [kswoll/WootzJs#20]
Hi Kirk!

I'd like to try wootzjs, it seems impressive!  
I have an updated windows 8.1 (x64) and a newly installed Visual Studio 2015 CTP5 on my laptop. 
I tried to follow the guidelines from "Getting started", but when i run build.bat unfortunately it gives many error messages. I've uploaded the result of building to onedrive, here is the url: http://1drv.ms/1M5ScEQ   . Could you please help me to solve these errors?
Thanks, 
Csaba

**Comment by kswoll** [comment]
Hi Csaba, thanks for your interest!  I'll take a look today and try checking out a clean slate and see if I can repro your issues.

**Comment by kswoll** [comment]
Thanks again for the bug report.  The build was indeed in a broken state.  I've changed the build.bat file to now point directly at the correct version of MsBuild (using v 14.0).  This solved some of the problems, and I fixed a few other issues in a few other csproj files to ensure everything builds again.  Please let me know if you have any further issues.

**Comment by csbeer** [comment]
Hi Kirk!
Thanks for the quick response! 
Tha situation is far better now! Only 3 build errors remained, two of them in Test projects and one is in Injection.  And there are many warnings... You can find the new log file here: http://1drv.ms/1E0MI8I

I tried to write and compile the HelloWorld app (.NET 4.5 Console app) by following "Getting started" page, but there is something wrong again, build process does not generate HelloWorld.js file.
Could you please check this, or review my project? you find it here: http://1drv.ms/16TRmL3
Here is the output of Build process:
1>------ Rebuild All started: Project: HelloWorld, Configuration: Debug Any CPU ------
1>  HelloWorld -> d:\projects\wootzjs\projects\HelloWorld\HelloWorld\bin\Debug\HelloWorld.exe
1>  
1>  Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
1>     at WootzJs.Compiler.Compiler.Main(String[] args) in d:\projects\wootzjs\source\WootzJs.Compiler\Compiler.cs:line 55
1>          1 file(s) copied.
1>  POSTBUILDSTEP for  COMPLETED OK
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========

Thanks for your efforts!
Csaba

ps: we can continue this conversation in emails... 
(you can find my email address on my profile page here on github)
